// <auto-generated />
using System;
using LuminaryVisuals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LuminaryVisuals.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241117191528_ClientEditingGuidelinesOptions")]
    partial class ClientEditingGuidelinesOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("WeeksToDueDateDefault")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.Archive", b =>
                {
                    b.Property<int>("ArchiveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArchiveId"));

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArchiveId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("Archives", (string)null);
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.CalculationOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationParameterId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("numeric");

                    b.Property<string>("OptionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalculationParameterId");

                    b.ToTable("CalculationOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalculationParameterId = 1,
                            Multiplier = 0.9m,
                            OptionName = "Straight Forward Linear, little mixing"
                        },
                        new
                        {
                            Id = 2,
                            CalculationParameterId = 1,
                            Multiplier = 1m,
                            OptionName = "Hybrid Mostly Linear"
                        },
                        new
                        {
                            Id = 3,
                            CalculationParameterId = 1,
                            Multiplier = 1.2m,
                            OptionName = "Movie with heavy SFX + VFX"
                        },
                        new
                        {
                            Id = 4,
                            CalculationParameterId = 2,
                            Multiplier = 1m,
                            OptionName = "0%"
                        },
                        new
                        {
                            Id = 5,
                            CalculationParameterId = 2,
                            Multiplier = 0.95m,
                            OptionName = "30%"
                        },
                        new
                        {
                            Id = 6,
                            CalculationParameterId = 2,
                            Multiplier = 0.85m,
                            OptionName = "60%"
                        },
                        new
                        {
                            Id = 7,
                            CalculationParameterId = 2,
                            Multiplier = 0.7m,
                            OptionName = "100%"
                        },
                        new
                        {
                            Id = 8,
                            CalculationParameterId = 3,
                            Multiplier = 1m,
                            OptionName = "1080p"
                        },
                        new
                        {
                            Id = 9,
                            CalculationParameterId = 3,
                            Multiplier = 1.05m,
                            OptionName = "Mixed"
                        },
                        new
                        {
                            Id = 10,
                            CalculationParameterId = 3,
                            Multiplier = 1.1m,
                            OptionName = "4k"
                        },
                        new
                        {
                            Id = 11,
                            CalculationParameterId = 4,
                            Multiplier = 1.15m,
                            OptionName = "Needs work"
                        },
                        new
                        {
                            Id = 12,
                            CalculationParameterId = 4,
                            Multiplier = 1.05m,
                            OptionName = "Mostly good"
                        },
                        new
                        {
                            Id = 13,
                            CalculationParameterId = 4,
                            Multiplier = 1m,
                            OptionName = "Great"
                        },
                        new
                        {
                            Id = 14,
                            CalculationParameterId = 4,
                            Multiplier = 0.9m,
                            OptionName = "Excellent"
                        });
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.CalculationParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParameterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CalculationParameter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultValue = 1.0m,
                            Description = "Highlights Difficulty ",
                            Name = "HighlightsDifficulty",
                            ParameterType = "Option"
                        },
                        new
                        {
                            Id = 2,
                            DefaultValue = 1.0m,
                            Description = "Pre-Parts Percentage",
                            Name = "PrePartsPercentage",
                            ParameterType = "Option"
                        },
                        new
                        {
                            Id = 3,
                            DefaultValue = 1.0m,
                            Description = "Resolution of video",
                            Name = "Resolution",
                            ParameterType = "Option"
                        },
                        new
                        {
                            Id = 4,
                            DefaultValue = 1.0m,
                            Description = "Quality of Footage",
                            Name = "FootageQuality",
                            ParameterType = "Option"
                        },
                        new
                        {
                            Id = 5,
                            DefaultValue = 0.3m,
                            Description = "Multiplier for camera when there exist more than 2",
                            Name = "CameraMulti",
                            ParameterType = "Decimal"
                        },
                        new
                        {
                            Id = 6,
                            DefaultValue = 0.4m,
                            Description = "Multiplier for raw footage size when bigger than 300gb",
                            Name = "SizeMulti",
                            ParameterType = "Decimal"
                        });
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatId"));

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEditorMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.HasKey("ChatId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.ClientEditingGuidelines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlackAndWhite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorReferences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrossFades")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoubleExposure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FadeToBlack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilmReferences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HighlightsFilm")
                        .HasColumnType("boolean");

                    b.Property<string>("LensFlares")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaskingTransitions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusicGenresArtists")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldFilmLook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OtherTransitions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureInPicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SongSamples")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoundDesignComments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoundDesignEmphasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpeechComments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransitionComments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UseSpeeches")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.Property<string>("VideoStructure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebsiteLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ClientEditingGuidelines", (string)null);
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.ClientPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("BillableHours")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ClientPaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PaymentVisibleClient")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProjectTotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PaymentId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("ClientPayment", (string)null);
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.EditorPayments", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("EditorDatePaid")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Overtime")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("WorkingHours")
                        .HasColumnType("numeric");

                    b.Property<bool>("isPaid")
                        .HasColumnType("boolean");

                    b.HasKey("PaymentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("EditorPayments", (string)null);
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal>("BillableHours")
                        .HasColumnType("numeric");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryEditorId")
                        .HasColumnType("text");

                    b.Property<int>("ProgressBar")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SecondaryEditorId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShootDate")
                        .IsRequired()
                        .HasColumnType("DATE");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WorkingMonth")
                        .HasColumnType("DATE");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ConversionRateUSToLek")
                        .IsRequired()
                        .HasColumnType("numeric");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.UserNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("UserNote");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.Archive", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.Project", "Project")
                        .WithOne("Archive")
                        .HasForeignKey("LuminaryVisuals.Data.Entities.Archive", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.CalculationOption", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.CalculationParameter", null)
                        .WithMany("Options")
                        .HasForeignKey("CalculationParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.Chat", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.Project", "Project")
                        .WithMany("Chats")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.ClientEditingGuidelines", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.ClientPayment", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", null)
                        .WithMany("Payments")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("LuminaryVisuals.Data.Entities.Project", "Project")
                        .WithOne("ClientPayment")
                        .HasForeignKey("LuminaryVisuals.Data.Entities.ClientPayment", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.EditorPayments", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.Project", "Project")
                        .WithMany("EditorPayments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", "User")
                        .WithMany("EditorPayments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.Setting", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.UserNote", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", null)
                        .WithMany("CreatedNotes")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LuminaryVisuals.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("CreatedNotes");

                    b.Navigation("EditorPayments");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.CalculationParameter", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("LuminaryVisuals.Data.Entities.Project", b =>
                {
                    b.Navigation("Archive")
                        .IsRequired();

                    b.Navigation("Chats");

                    b.Navigation("ClientPayment")
                        .IsRequired();

                    b.Navigation("EditorPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
